name: Delete Workflow Runs

on:
  workflow_dispatch: # 支持手动一键点击运行

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write   # 必须赋予 actions 写权限
      contents: read
    steps:
      - name: 批量删除工作流记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0           # 保留天数设为 0（即清理全部旧记录）
          keep_minimum_runs: 2     # 保留最近的 2 次记录防误删（可按需改为 0 或 1）
